/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20StubSol from "./ERC20Stub.sol";
export type { erc20StubSol };
import type * as stubContractSol from "./StubContract.sol";
export type { stubContractSol };
export type { Erc721Stub } from "./Erc721Stub";
export type { EscrowStub } from "./EscrowStub";
export type { IERC20 } from "./IERC20";
export type { WETH9 } from "./WETH9";
