import "./arbitrum/Arbitrum.tasks";
import "./Deploy.tasks";
import "./gnosis_safe/Safe.tasks";
import "./1inch/Swap.tasks";
import "./rage_trade/RageTrade.tasks";
import "./zksync/zkSyncLite.tasks";
import "./zksync/zkSyncEra.tasks";
import "./stargate/stargate.tasks";
import "./routes/ArbitrumRoutes.tasks";
import "./routes/GeneralRoutes.tasks";
import "./socket_bungee/socket.tasks";
import "./ens/ens.tasks";
import "./misc/misc.tasks";
import "./scroll/scroll_sepolia.tasks";
import "./scroll/scroll.tasks";
import "./ens/arbId.tasks";
import "./ens/arbId.tasks";
import "./ens/opNames.tasks";
import "./orbiter/orbiter.tasks"
import "./taiko/taiko_alpha_2.tasks"
import "./linea/linea_goerli.tasks"
import "./zora/zoraNetwork.tasks"
import "./zora/zoraEthereum.tasks"
import "./arbitrum/ArbDoge.tasks"
import "./arbitrum/RektArb.tasks"
import "./arbitrum/LSDoge.tasks"
import "./arbitrum/BruhArb.tasks"
import "./layerZero/layerZero.tasks"
import "./snapshot/snapshot.tasks"
import "./love/love.tasks"
import "./zkEvm/zkEvm.tasks"
import "./holograph/holograph.tasks"
import "./publicGoodsNetwork/pgn.tasks"
import "./polyhedra/zkBridge.tasks"
import "./linea/linea_mainnet.tasks"
import "./coinbase/base_goerli.tasks"
import "./coinbase/base_mainnet.tasks"
import "./coinbase/base_mainnet_summer.tasks"
import "./philand/philand.tasks"
import "./arbitrum/ArbitrumStylusSepolia.tasks"
import "./starknet/startknet.tasks"
import "./uniswap/uniswap.tasks"
import "./syncswap/syncswap.tasks"
import "./metamask/metamask.tasks"
import "./intract/intract.tasks"
import "./kyberSwap/kyberSwap.tasks"